<?php
// Auto-generated by SalesOS Settings — do not edit manually.
// Last generated: 2026-06-26 07:17:01
// Regenerate: Admin → SalesOS → Settings → Save
return [
    'db_host' => 'localhost',
    'db_port' => 3306,
    'db_name' => 'crm',
    'db_user' => 'crm_user',
    'db_pass' => 'xY5qRq5DFtiGto.m',
    'db_prefix' => 'tbl',
    'redis_host' => '127.0.0.1',
    'redis_port' => 6379,
    'redis_password' => '',
    'ami_host' => '103.42.4.210',
    'ami_port' => 5038,
    'ami_user' => 'crm-api',
    'ami_secret' => 'CRM_AMI_S3cr3t#2024',
    'pbx_id' => 'pbx-01',
    'pbx_name' => 'Main PBX',
    'ws_port' => 8082,
    'stream_maxlen' => 50000,
];
